SELECT USRL.ID_ROLE
		, USRL.ID_USER 
		, US.LOGIN_NAME
		, US.NAME AS NM_USER
		, US.PASSWORD
		, RL.NAME AS ROLE_NAME
FROM TB_USERS_ROLES AS USRL
	INNER JOIN TB_USERS AS US
		ON US.ID = USRL.ID_USER
	INNER JOIN TB_ROLES AS RL
		ON RL.ID = USRL.ID_ROLE
WHERE 1=1
	AND US.LOGIN_NAME = '{0}'
	AND US.PASSWORD = '{1}'
	


	